name: First Workflow

on: [push]

jobs:
  build-ubuntu-20.04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running on Ubuntu 20.04"

  build-ubuntu-22.04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running on Ubuntu 22.04"

  build-ubuntu-18.04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running on Ubuntu 18.04"
